REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\Sample_wraped_text\Sample_wraped_text.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\Sample_wraped_text\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\Sample_wraped_text\include" -I "D:\MyGitHub\Sample_wraped_text\include\service" -I "D:\MyGitHub\Sample_wraped_text\include\component" -I "D:\MyGitHub\Sample_wraped_text\ResID" -I "D:\MyGitHub\Sample_wraped_text\src\app\widget" -I "D:\MyGitHub\Sample_wraped_text\src\app\launcher" -I "D:\MyGitHub\Sample_wraped_text\src\app\wallpaper" -I "D:\MyGitHub\Sample_wraped_text\src\app\screen_lock" -I "D:\MyGitHub\Sample_wraped_text\include\service" -I "D:\MyGitHub\Sample_wraped_text\include\component" -I "D:\MyGitHub\Sample_wraped_text\include\service" -I "D:\MyGitHub\Sample_wraped_text\src\framework" -I "D:\MyGitHub\Sample_wraped_text\src\framework\ui_core\base" -I "D:\MyGitHub\Sample_wraped_text\src\framework\ui_core\mvc" -I "D:\MyGitHub\Sample_wraped_text\src\framework\ui_core\pme" -I "D:\MyGitHub\Sample_wraped_text\src\framework\mmi_core" -I "D:\MyGitHub\Sample_wraped_text\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Sample_wraped_text\src\component" -I "D:\MyGitHub\Sample_wraped_text\src\ui_engine\framework\xml" -I "D:\MyGitHub\Sample_wraped_text"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\Sample_wraped_text\arm\Sample_wraped_text.o" -c "d:\MyGitHub\Sample_wraped_text\Sample_wraped_text.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\Sample_wraped_text\include" -I "D:\MyGitHub\Sample_wraped_text\include\service" -I "D:\MyGitHub\Sample_wraped_text\include\component" -I "D:\MyGitHub\Sample_wraped_text\ResID" -I "D:\MyGitHub\Sample_wraped_text\src\app\widget" -I "D:\MyGitHub\Sample_wraped_text\src\app\launcher" -I "D:\MyGitHub\Sample_wraped_text\src\app\wallpaper" -I "D:\MyGitHub\Sample_wraped_text\src\app\screen_lock" -I "D:\MyGitHub\Sample_wraped_text\include\service" -I "D:\MyGitHub\Sample_wraped_text\include\component" -I "D:\MyGitHub\Sample_wraped_text\include\service" -I "D:\MyGitHub\Sample_wraped_text\src\framework" -I "D:\MyGitHub\Sample_wraped_text\src\framework\ui_core\base" -I "D:\MyGitHub\Sample_wraped_text\src\framework\ui_core\mvc" -I "D:\MyGitHub\Sample_wraped_text\src\framework\ui_core\pme" -I "D:\MyGitHub\Sample_wraped_text\src\framework\mmi_core" -I "D:\MyGitHub\Sample_wraped_text\src\ui_engine\vrt\interface" -I "D:\MyGitHub\Sample_wraped_text\src\component" -I "D:\MyGitHub\Sample_wraped_text\src\ui_engine\framework\xml" -I "D:\MyGitHub\Sample_wraped_text"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\Sample_wraped_text\Sample_wraped_text.axf"  "D:\MyGitHub\Sample_wraped_text\arm\gccmain.o"  "D:\MyGitHub\Sample_wraped_text\arm\Sample_wraped_text.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perpro.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persso.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\Sample_wraped_text\Sample_wraped_text.pkd" -e AXF "D:\MyGitHub\Sample_wraped_text\Sample_wraped_text.vcproj" "D:\MyGitHub\Sample_wraped_text\Sample_wraped_text.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\Sample_wraped_text\Sample_wraped_text.vcproj" "Sample_wraped_text" "0.1.0" "RDZDX" "500" "NotSupportBg" "Not Support rotate" "Sample_wraped_text" "Sample_wraped_text" "Sample_wraped_text" "9000000000000000" "content" " ProMng sso" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\Sample_wraped_text\arm D:\MyGitHub\Sample_wraped_text\build.log

